# Use the latest version of Ubuntu as the base image
FROM ubuntu:22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update package lists, install basic tools, toolchains, stlink-tools, and clean up
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    gcc-arm-none-eabi \
    gdb-multiarch \
    autoconf \
    libc6-dev \
    automake \
    curl \
    build-essential \
    git \
    wget \
    libtool \
    make \
    pkg-config \
    ca-certificates \
    software-properties-common \
    clang-format \
    clang-tidy \
    pmccabe \
    python3 \
    python3-pip \
    stlink-tools \
    cmake \
    xz-utils \
    ninja-build && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install setuptools

# Enable the universe repository and update the package list
RUN apt-get update -y \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y universe \
    && apt-get update -y

# Install libnewlib-arm-none-eabi and libnewlib-dev
RUN apt-get install -y libnewlib-dev \ 
    && apt-get install -y libnewlib-arm-none-eabi

# Set the working directory
WORKDIR /workspace

# Copy your project files into the container
COPY . /workspace

# Change to the Modules subdirectory
WORKDIR /workspace/STM32L4_FREERTOS
